### PR TITLE
Swift5 migration

### PR DESCRIPTION
**Pull request by Nabeatsu**

### CODE REVIEW

**Comment by ratulSharker** [comment]
@Krisiacik  please accept this, currently i'm using this pull request as: 

```
pod 'ImageViewer', :git=> 'https://github.com/Nabeatsu/ImageViewer', :branch=> 'master' 
```

**Comment by ramonvic** [comment]
Any News on that?

**Comment by H3ndrx** [comment]
Would be awesome if you could merge it :)

**Comment by RuiAAPeres** [comment]
This has been merged. Thank you for the contribution.

**Pull request closed without merging**
